%=================================================================
% 情報システム学会 研究発表大会 原稿用テンプレート(TeXスタイル)
%     ISSJ実行委員会/プログラム委員会(ISSJ学会誌編集委員会)
% issj2012.sty Ver. 0.50 2012-10-12 Tadashi Iijima (iijima@ae.keio.ac.jp)
% issj2012.sty Ver. 0.60 2012-10-15 Tadashi Iijima (iijima@ae.keio.ac.jp)
% issj2012.sty Ver. 0.70 2012-10-19 Tadashi Iijima (iijima@ae.keio.ac.jp)
% issj2012.sty Ver. 0.80 2012-10-20 Tadashi Iijima (iijima@ae.keio.ac.jp)
%=================================================================
\LoadClass[11pt,a4j]{jarticle}
\ProvidesClass{issj}[2020/10/23 Ver.0.8]
\input{issj.sty}
\endinput
%=================================================================
